### ISSUE TITLE
Seed Analyzer GUI won't open. (Version mismatch with InfinityLib.)

### ISSUE THREAD

**Issue by warpath1985** [AgriCraft/AgriCraft#1046]
getting no gui on the seed analyser making it unusable 
version -agricraft-2.0.0-0.10.0-a19

**Comment by warpath1985** [comment]
found temporary work around using hoppers o input the seeds and journal and unload seeds once analysed

**Comment by Darianna77** [comment]
Yeah have the same problem :(  Will make me 2 hoppers and test it..

**Comment by Ockman** [comment]
I also have this problem with agricraft-2.0.0-0.10.0-a19.

**Comment by idgarad** [comment]
throws:

[20:50:13] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: com.infinityraider.infinitylib.container.ContainerBase.<init>(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraft/entity/player/InventoryPlayer;II)V
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NoSuchMethodError: com.infinityraider.infinitylib.container.ContainerBase.<init>(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraft/entity/player/InventoryPlayer;II)V
        at com.infinityraider.agricraft.container.ContainerSeedAnalyzer.<init>(ContainerSeedAnalyzer.java:42) ~[ContainerSeedAnalyzer.class:?]
        at com.infinityraider.agricraft.handler.GuiHandler.getServerGuiElement(GuiHandler.java:47) ~[GuiHandler.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:251) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:87) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2494) ~[zs.class:?]
        at com.infinityraider.agricraft.blocks.BlockSeedAnalyzer.func_180639_a(BlockSeedAnalyzer.java:110) ~[BlockSeedAnalyzer.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:451) ~[lv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
        ... 5 more

**Comment by MBelhardi** [comment]
I've found the problem why the seed analyzer won't open. The problem is with "InfinityLib" (Version 0.11.0) which is needed for Agricraft. When you use an older Version of "InfinityLib" (0.10.0) you will be able to open the gui without problem.

**Comment by CheleGohm** [comment]
I had the same issue.  No errors, just no GUI.  Downgraded the InfinityLib to version 0.10.0 and it works.

**Comment by janagyjr** [comment]
Having the same issue (MC 1.10.2, forge 2488), downgrading InfinityLib to version 0.10.0 fixed the problem.

**Comment by CodesCubesAndCrashes** [comment]
Releases a20 onward have this fixed. I'm hoping to have a stable and official release soon!

**Comment by Jeppeskovsgaard** [comment]
After updating to a21, the analyzer now works, but the Rice Seeds/plants from Actually Additions can no longer be harvested by right clicking rice planted in crop sticks.

**Comment by CodesCubesAndCrashes** [comment]
@Jeppeskovsgaard Is the harvesting blocked regardless of what you're holding in your hand? Or only if you are holding a specific item? And which plants work normally? In contrast to the rice.

Also, this sounds like an unrelated problem, so it should have it's own issue, no?
