### ISSUE TITLE
Agricraft crashes game when crafting recipe

### ISSUE THREAD

**Issue by Magi1053** [AgriCraft/AgriCraft#1071]
```
Description: Rendering ingredient

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:720)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:170)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:141)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:125)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:97)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:156)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1925_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Reflector.callVoid(Reflector.java:529)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1417)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.VertexBuffer.func_178977_d(VertexBuffer.java:720)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at net.minecraft.client.renderer.RenderItem.func_175045_a(RenderItem.java:170)
	at net.minecraft.client.renderer.RenderItem.func_175036_a(RenderItem.java:141)

-- Ingredient being rendered --
Details:
	Ingredient Mod: AgriCraft
	Ingredient Info: 1xtile.agricraft:water_channel_valve@0 agricraft:water_channel_valve nbt:{agri_material_meta:9,agri_material:"chisel:planks-oak"}
Stacktrace:
	at mezz.jei.gui.ingredients.GuiIngredientFast.createRenderIngredientException(GuiIngredientFast.java:370)
	at mezz.jei.gui.ingredients.GuiIngredientFast.renderItemAndEffectIntoGUI(GuiIngredientFast.java:99)
	at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:156)
	at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305)
	at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1925_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:73)
	at slimeknights.mantle.client.gui.GuiMultiModule.func_73863_a(GuiMultiModule.java:173)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Reflector.callVoid(Reflector.java:529)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1417)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Item trying to craft is a MekanismGenerators Advanced Solar Generator
![image](https://user-images.githubusercontent.com/1045179/30388461-70c33f54-9875-11e7-9729-8c02e9dce7e2.png)
Trying to craft in TinkersConstruct Crafting Station

**Comment by Magi1053** [comment]
Possibly related https://github.com/SlimeKnights/TinkersConstruct/issues/3155

**Comment by darthvader45** [comment]
In this case, it may be a conflict with TiCon and Mekanism.  Don't think Agricraft has anything to do with this.  Have you tried with just Agricraft and Mekanism?

**Comment by Magi1053** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/2776
