### ISSUE TITLE
crach au démarrage

### ISSUE THREAD

**Issue by nouveau0** [AgriCraft/AgriCraft#1089]
Bonjours, je suis sous la version 1.7.10 de minecraft et la version 10.13.4.1614-1.7.10 de forge.
Je sais elle et vielle mais thaumcraft4 n'existent pas audela.
J'ai  ajouter AgriCraft ce matin a mes mod et depuis j'ai un crach au démarrage, je ne comprend pas pour quoi. Pouvez-vous m'aider? 
Merci
Bonne journée

---- Minecraft Crash Report ----
Time: 31/12/17 10:26
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/InfinityRaider/AgriCraft/blocks/BlockCrop
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/InfinityRaider/AgriCraft/blocks/BlockCrop
	at com.InfinityRaider.AgriCraft.AgriCraft.preInit(AgriCraft.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: com.InfinityRaider.AgriCraft.blocks.BlockCrop
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: vazkii.botania.api.item.IHornHarvestable
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at weatherpony.partial.asmedit.ExtentionListenerTransformer.transform(ExtentionListenerTransformer.java:51)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 39 more
Caused by: java.lang.ClassNotFoundException: vazkii.botania.api.item.IHornHarvestable
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at weatherpony.partial.asmedit.ExtentionListenerTransformer.transform(ExtentionListenerTransformer.java:47)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_144, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 198627784 bytes (189 MB) / 571555840 bytes (545 MB) up to 2120679424 bytes (2022 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCH	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCH	FastCraft{1.23} [FastCraft] (FastCraft-Mod-1.7.10.jar) 
	UCH	gilded-games-util{1.7.10-1.1} [Gilded Games Utility] (gilded-games-util.jar) 
	UCH	seasonsmod{pre-3.0beta4} [The Seasons Mod] (1.7.10-TheSeasonsMod-pre-3.0beta4.pmlm) 
	UCH	seasonsmodac{1.0} [Additional Seasons Content] (1.7.10-TheSeasonsMod-pre-3.0beta4.pmlm) 
	UCH	wputil{1.4} [WeatherPony Utilities] (1.7.10-TheSeasonsMod-pre-3.0beta4.pmlm) 
	UCH	Waila{1.5.3} [Waila] (_Waila-Mod-1.7.10.jar) 
	UCE	AgriCraft{1.7.10-1.5.0} [AgriCraft] (AgriCraft-1.7.10-1.5.0.jar) 
	UCH	tennox_chameleon{1.2} [Chameleon Blocks] (Chameleon-Blocks-Mod-1.7.10.jar) 
	UCH	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCH	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCH	endercrop{1.7.10-1.1} [Ender Crop] (endercrop-1.7.10-1.2.jar) 
	UCH	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCH	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCH	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5 (1).jar) 
	UCH	gadomancy{1.0.7.3} [Gadomancy] (gadomancy-1.7.10-1.0.7.3.jar) 
	UCH	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCH	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UCH	yurtmod{1.11} [Nomadic Tents] (NomadicTents[1.7.10]-1.11.jar) 
	UCH	StorageDrawers{1.7.10-1.10.7} [Storage Drawers] (StorageDrawers-1.7.10-1.10.7.jar) 
	UCH	TaintedMagic{r7.6} [Tainted Magic] (Tainted-Magic-r7.6.jar) 
	UCH	TConstruct{1.7.10-1.7.1.build748} [Tinkers' Construct] (TConstruct-1.7.10-1.7.1.jar) 
	UCH	ThaumicHorizons{1.1.9} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.9.jar) 
	UCH	ani_siege{v1.0} [Siege] (The-Siege-Mod-1.7.10.jar) 
	UCH	WailaHarvestability{1.1.6} [Waila Harvestability] (Waila-Harvestability-Mod-1.7.10.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4432' Renderer: 'Intel(R) HD Graphics 4400'
	CoFHCore: -[1.7.10]3.1.4-329
	Mantle Environment: Environment healthy.
	TConstruct Environment: Environment healthy.

**Comment by InfinityRaider** [comment]
Please use English, and no 1.7.10 is no longer being looked into by me atm.
