### ISSUE TITLE
Crash with TileEntitySeedAnalyzer and BlockDietHopper

### ISSUE THREAD

**Issue by Sir-Will** [AgriCraft/AgriCraft#1241]
Using a hopper with the seed analyzer causes the following crash.

AgriCraft-2.12.0-1.12.0-a6
diethopper-1.1
```
java.lang.IncompatibleClassChangeError: Conflicting default methods: net/minecraft/inventory/IInventory.bridge$getRootLens net/minecraftforge/items/IItemHandler.bridge$getRootLens
	at com.infinityraider.agricraft.tiles.analyzer.TileEntitySeedAnalyzer.bridge$getRootLens(TileEntitySeedAnalyzer.java)
	at org.spongepowered.common.item.inventory.adapter.InventoryAdapter.bridge$getSlot(InventoryAdapter.java:64)
	at org.spongepowered.common.event.SpongeCommonEventFactory.captureTransaction(SpongeCommonEventFactory.java:1435)
	at net.minecraft.tileentity.TileEntityHopper.redirect$impl$throwEventsForInsertion$zkm000(TileEntityHopper.java:1844)
	at net.minecraft.tileentity.TileEntityHopper.func_174918_a(TileEntityHopper.java:417)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:216)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4739)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlk000(WorldServer.java:4723)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3941)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.infinityraider.agricraft.tiles.analyzer.TileEntitySeedAnalyzer.bridge$getRootLens(TileEntitySeedAnalyzer.java)
	at org.spongepowered.common.item.inventory.adapter.InventoryAdapter.bridge$getSlot(InventoryAdapter.java:64)
	at org.spongepowered.common.event.SpongeCommonEventFactory.captureTransaction(SpongeCommonEventFactory.java:1435)
	at net.minecraft.tileentity.TileEntityHopper.redirect$impl$throwEventsForInsertion$zkm000(TileEntityHopper.java:1844)
	at net.minecraft.tileentity.TileEntityHopper.func_174918_a(TileEntityHopper.java:417)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:216)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:237)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:4739)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zlk000(WorldServer.java:4723)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // pl.asie.foamfix.common.TileEntityFasterHopper
	Block type: ID #154 (tile.hopper // com.rwtema.diethopper.BlockDietHopper // minecraft:hopper)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (5375,84,2809), Chunk: (at 15,5,9 in 335,175; contains blocks 5360,0,2800 to 5375,255,2815), Region: (10,5; contains chunks 320,160 to 351,191, blocks 5120,0,2560 to 5631,255,3071)
	Actual block type: ID #154 (tile.hopper // com.rwtema.diethopper.BlockDietHopper // minecraft:hopper)
	Actual block data value: 3 / 0x3 / 0b0011
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3941)
```

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
