### ISSUE TITLE
Description: Ticking block entity

### ISSUE THREAD

**Issue by NNM42** [AgriCraft/AgriCraft#1257]
MC 1.12.2
Agricraft 2.12.0-1.12.0-a6
*ModPack PO3*
java.lang.AbstractMethodError: Method com/infinityraider/agricraft/tiles/analyzer/TileEntitySeedAnalyzer.getStackInSlot(I)Lnet/minecraft/item/ItemStack; is abstract
	at com.infinityraider.agricraft.tiles.analyzer.TileEntitySeedAnalyzer.getStackInSlot(TileEntitySeedAnalyzer.java)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transfer(InventoryHelper.java:64)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processPosition(TransferNodeItem.java:168)
	at com.rwtema.extrautils2.transfernodes.TransferNodeItem.processPosition(TransferNodeItem.java:36)
	at com.rwtema.extrautils2.transfernodes.TransferNodeBase.func_73660_a(TransferNodeBase.java:164)
	at com.rwtema.extrautils2.transfernodes.TileTransferHolder.func_73660_a(TileTransferHolder.java:67)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
