### ISSUE TITLE
Create 0.5d incompatible with AgriCraft latest version [1.18.2]

### ISSUE THREAD

**Issue by squoshi** [AgriCraft/AgriCraft#1478]
## Quick description
AgriCraft tried to fire "MECHANICAL_HARVESTER' event, logs as java.lang.NoSuchField error

## Related issues and searches
None

## Mods and versions used
* Minecraft: 1.18.2
* AgriCraft: 3.1.4
* InfinityLib: 2.1.4
* Create: 0.5d

## Steps to replicate the issue
1. Install AgriCraft 3.1.4 and Create 0.5d (also recommend Not Enough Crashes)
2. Launch game

## Expectations and explanations
'MECHANICAL_HARVESTER' is invalid.

## Your environment
* How are you playing?
  * Operating System: Windows 10
  * Launcher: Curseforge
  * Modpack: Custom

## Links to crash logs, stack traces, etc
[latest.log](https://github.com/AgriCraft/AgriCraft/files/9561651/latest.log)
Highlight:
```
java.lang.NoSuchFieldError: MECHANICAL_HARVESTER
	at TRANSFORMER/agricraft@1.18.2-3.1.3/com.infinityraider.agricraft.plugins.create.CreateCompat.injectAgriHarvesterMovementBehaviour(CreateCompat.java:15)
```

**Comment by drewhoener** [comment]
Same issue, same versions
```Stacktrace:
        at com.infinityraider.agricraft.plugins.create.CreateCompat.injectAgriHarvesterMovementBehaviour(CreateCompat.java:15) ~[agricraft-1.18.2-3.1.4.jar%2348!/:3.1.4] {re:classloading}
-- MOD agricraft --
Details:
        Mod File: /home/drew/ATM7/mods/agricraft-1.18.2-3.1.4.jar
        Failure message: AgriCraft (agricraft) encountered an error during the common_setup event phase
                java.lang.NoSuchFieldError: MECHANICAL_HARVESTER
        Mod Version: 1.18.2-3.1.4
        Mod Issue URL: https://github.com/AgriCraft/AgriCraft/issues/
        Exception message: java.lang.NoSuchFieldError: MECHANICAL_HARVESTER
Stacktrace:
        at com.infinityraider.agricraft.plugins.create.CreateCompat.injectAgriHarvesterMovementBehaviour(CreateCompat.java:15) ~[agricraft-1.18.2-3.1.4.jar%2348!/:3.1.4] {re:classloading}
        at com.infinityraider.agricraft.plugins.create.CreatePlugin.onCommonSetupEvent(CreatePlugin.java:28) ~[agricraft-1.18.2-3.1.4.jar%2348!/:3.1.4] {re:classloading}
        at com.infinityraider.agricraft.impl.v1.PluginHandler.lambda$onCommonSetup$2(PluginHandler.java:48) ~[agricraft-1.18.2-3.1.4.jar%2348!/:3.1.4] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
        at java.util.concurrent.ConcurrentLinkedDeque$CLDSpliterator.forEachRemaining(ConcurrentLinkedDeque.java:1483) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
        at com.infinityraider.agricraft.impl.v1.PluginHandler.executeForPlugins(PluginHandler.java:68) ~[agricraft-1.18.2-3.1.4.jar%2348!/:3.1.4] {re:classloading}
        at com.infinityraider.agricraft.impl.v1.PluginHandler.onCommonSetup(PluginHandler.java:48) ~[agricraft-1.18.2-3.1.4.jar%2348!/:3.1.4] {re:classloading}
        at com.infinityraider.agricraft.proxy.IProxy.onCommonSetupEvent(IProxy.java:33) ~[agricraft-1.18.2-3.1.4.jar%2348!/:3.1.4] {re:classloading}
        at com.infinityraider.infinitylib.InfinityMod.onCommonSetupEvent(InfinityMod.java:375) ~[infinitylib-2.1.4.jar%23182!/:2.1.4] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.74.jar%23350!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.74.jar%23349!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

**Comment by agentwolf88** [comment]
Same

**Comment by reenigne1** [comment]
same issue, also reported it on the cursehub page
[crash-2022-12-09_21.45.22-fml.txt](https://github.com/AgriCraft/AgriCraft/files/10199086/crash-2022-12-09_21.45.22-fml.txt)
I tried the the fix that involved rolling back the version of create and create related mods, unfortunately I was unable to get back to a version of agricraft and create that both work with a compatible version of forge

**Comment by reenigne1** [comment]
> #Set to false to disable compatibility with Create (in case things break)
> "Enable Create compat" = false
> #
> ```
> 
> This allows you to play with both mods enabled, but you won't be able to use the create harvester on crop sticks etc.

Effective workaround, thanks!

**Comment by Enderdraak** [comment]
I hope this gets fixed soon. I would like to use these mods together. And my knowledge of Java is too bad for me to attempt to fix it myself.

**Comment by Enderdraak** [comment]
I have been deeping deeper. And I have honestly no clue how to program Java. The problem seems to come from the following code [source (lines 27 to 38)](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/AllMovementBehaviours.java):
```	public static void registerBehaviour(ResourceLocation block, MovementBehaviour behaviour) {
		BLOCK_BEHAVIOURS.register(block, behaviour);
	}

	public static void registerBehaviour(Block block, MovementBehaviour behaviour) {
		BLOCK_BEHAVIOURS.register(block, behaviour);
	}

	@Deprecated(forRemoval = true)
	public static void registerBehaviour(IRegistryDelegate<Block> block, MovementBehaviour behaviour) {
		registerBehaviour(block.name(), behaviour);
	}
```
This code seems to have changed around the time the first time this issue was found.

**Comment by berkkrkc09** [comment]
Hey, I heve the same problem with create 0.5.0.h and AgriCraft 3.1.4. I hope This gets fixed soon. Here's the crash log: https://gist.github.com/berkkrkc09/3e6623f56c2677baeeac06de5e07ef2f

**Comment by Dokman** [comment]
> I have been deeping deeper. And I have honestly no clue how to program Java. The problem seems to come from the following code [source (lines 27 to 38)](https://github.com/Creators-of-Create/Create/blob/mc1.18/dev/src/main/java/com/simibubi/create/AllMovementBehaviours.java):
> 
> ```
>         public static void registerBehaviour(ResourceLocation block, MovementBehaviour behaviour) {
> 		BLOCK_BEHAVIOURS.register(block, behaviour);
> 	}
> 
> 	public static void registerBehaviour(Block block, MovementBehaviour behaviour) {
> 		BLOCK_BEHAVIOURS.register(block, behaviour);
> 	}
> 
> 	@Deprecated(forRemoval = true)
> 	public static void registerBehaviour(IRegistryDelegate<Block> block, MovementBehaviour behaviour) {
> 		registerBehaviour(block.name(), behaviour);
> 	}
> ```
> 
> This code seems to have changed around the time the first time this issue was found.

i'm diving trying to fix and update the mod

**Comment by Dokman** [comment]
@Ketheroth 
The supplied phased action failed with an exception.
Could not resolve all files for configuration ':runtimeClasspathCopy'.
Could not resolve mezz.jei:jei-1.18.2:9.5.3.153_mapped_parchment_2022.11.06-1.18.2.
Required by:
    project :
Cannot find a version of 'mezz.jei:jei-1.18.2' that satisfies the version constraints:
   Dependency path 'com.infinityraider.agricraft:AgriCraft:1.18.2-3.1.4' --> 'mezz.jei:jei-1.18.2:9.5.3.153_mapped_parchment_2022.11.06-1.18.2'
   Dependency path 'com.infinityraider.agricraft:AgriCraft:1.18.2-3.1.4' --> 'com.infinityraider.infinitylib:InfinityLib:2.1.4' (runtimeElements) --> 'mezz.jei:jei-1.18.2:{strictly 9.5.3.153_mapped_parchment_2022.03.13-1.18.2}'

when i tryed to compile your branch

**Comment by Ketheroth** [comment]
you need to edit two files in InfinityLib:
- mod.properties: change mapping_version to be 2022.11.06-1.18.2
- build.gradle: change forge dependency version to be 1.18.2-40.1.76

**Comment by Dokman** [comment]
I'll try it
