### ISSUE TITLE
Crash with Crop : NPE

### ISSUE THREAD

**Issue by SpyMan10** [AgriCraft/AgriCraft#791]
`Description: Tesselating block model

java.lang.NullPointerException: Tesselating block model
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.func_188616_a(BakedInfBlockModel.java:65)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:101)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:72)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:52)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
	at codechicken.lib.render.block.CCExtendedBlockRendererDispatcher.func_175018_a(CCExtendedBlockRendererDispatcher.java:53)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:290)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(ChunkRenderWorker.java:119)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(ChunkRenderWorker.java:47)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.infinityraider.infinitylib.render.block.BakedInfBlockModel.func_188616_a(BakedInfBlockModel.java:65)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187498_b(BlockModelRenderer.java:101)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:107)

-- Block model being tesselated --
Details:
	Block: agricraft:crop[age=7,crosscrop=false]
	Block location: World: (249,64,-1963), Chunk: (at 9,4,5 in 15,-123; contains blocks 240,0,-1968 to 255,255,-1953), Region: (0,-4; contains chunks 0,-128 to 31,-97, blocks 0,0,-2048 to 511,255,-1537)
	Using AO: true`

**Comment by InfinityRaider** [comment]
Closing since we are moving to 1.16.
