### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Eufranio** [AgriCraft/AgriCraft#903]
This error appears on load:
```
>  [18:04:59] [Server thread/WARN] [org.reflections.Reflections]: could not create Vfs.Dir from url. ignoring the exception and continuing
org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [asmgen:/]
either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlTy
pe urlType) with your specialized UrlType.
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:109) ~[Vfs.class:?]
    at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) ~[Vfs.class:?]
    at org.reflections.Reflections.scan(Reflections.java:237) ~[Reflections.class:?]
    at org.reflections.Reflections.scan(Reflections.java:204) [Reflections.class:?]
    at org.reflections.Reflections.<init>(Reflections.java:129) [Reflections.class:?]
    at org.reflections.Reflections.<init>(Reflections.java:170) [Reflections.class:?]
    at org.reflections.Reflections.<init>(Reflections.java:143) [Reflections.class:?]
    at com.agricraft.agricore.util.ResourceHelper.<clinit>(ResourceHelper.java:21) [ResourceHelper.class:?]
    at com.infinityraider.agricraft.core.CoreHandler.preInit(CoreHandler.java:72) [CoreHandler.class:?]
    at com.infinityraider.agricraft.proxy.IProxy.preInitStart(IProxy.java:27) [IProxy.class:?]
    at com.infinityraider.infinitylib.InfinityMod.preInit(InfinityMod.java:88) [InfinityMod.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111-internal]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111-internal]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616) [FMLModContainer.class:?]
    at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111-internal]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111-internal]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111-internal]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111-internal]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111-internal]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111-internal]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
    at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552) [LoadController.class:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624) [Loader.class:?]
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328) [FMLCommonHandler.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) [ld.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111-internal]
>  [18:04:59] [Server thread/INFO] [org.reflections.Reflections]: Reflections took 246 ms to scan 107 urls, producing 68532 keys and 77997 values 

```

**Comment by RlonRyan** [comment]
Duplicate of closed issue #876. Reopening old issue and closing this as a duplicate.
