### ISSUE TITLE
Crash on startup - build a18

### ISSUE THREAD

**Issue by Kilmatar** [AgriCraft/AgriCraft#987]
Crash log here: [PASTEBIN](https://pastebin.com/LEaPwTjN)

In very short:

Description: Exception in server tick loop
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AgriCraft (agricraft)
Caused by: java.lang.NoSuchFieldError: DEFAULT_PLANT_ICON

**Comment by digitronics** [comment]
+1

[crash log](https://pastebin.com/CBRG5xBp)

**Comment by CodesCubesAndCrashes** [comment]
Since Google seems to suggest that freshly recompiling the jar to clear out any out of date class files can help, I've just made a new copy of the same branch. Can't test it on the go, but LMK if anyone tries this: 
[agricraft-2.0.0-0.10.0-a18.jar.txt](https://github.com/AgriCraft/AgriCraft/files/1055508/agricraft-2.0.0-0.10.0-a18.jar.txt) (take off the `.txt` after downloading).

**Comment by Psycholiquid71** [comment]
Thank you I will give it a try now

**Comment by Psycholiquid71** [comment]
New error now: 
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AgriCraft (agricraft)

Caused by: java.lang.NoSuchFieldError: IRON`

**Comment by CodesCubesAndCrashes** [comment]
@Psycholiquid71 Could you include the stack trace, or put the log file up on pastebin? Thanks!

**Comment by CocoVanChoco** [comment]
[https://pastebin.com/BGnLUgfi](https://pastebin.com/BGnLUgfi)

**Comment by RlonRyan** [comment]
Dang it... It's a @SideOnly thing... I need to get better at separating the client and server code.

**Comment by RlonRyan** [comment]
Wait... Wut... All the @SideOnly annotations that are needed are already there...

Oh wait... it's clinit... So apparently forge isn't doing its job properly when stripping static fields from classes!

I'll just make the field available on both sides for now since forge is being stupid...

**Comment by digitronics** [comment]
Any plans to do a release, or hotfix of some of the fixes over the next few days?

**Comment by SHOVELL** [comment]
when will this fix be available to download?

**Comment by CocoVanChoco** [comment]
@Shovell just stick with the #a17 release till it gets sorted with other stuff and then released.  Patience is the Key all over the world.

**Comment by sealchan1** [comment]
Looking forward to the fix (waiting patiently :-)).  My stack trace if useful...

Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from AgriCraft (agricraft)
Caused by: java.lang.NullPointerException
	at com.infinityraider.agricraft.core.JsonPlant.convertProductJSON(JsonPlant.java:215)
	at com.infinityraider.agricraft.core.JsonPlant$$Lambda$1094/1546283183.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.infinityraider.agricraft.core.JsonPlant.initProductListJSON(JsonPlant.java:210)
	at com.infinityraider.agricraft.core.JsonPlant.<init>(JsonPlant.java:54)
	at com.infinityraider.agricraft.core.CoreHandler$$Lambda$1089/2065379489.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1612)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.infinityraider.agricraft.core.CoreHandler.initPlants(CoreHandler.java:133)
	at com.infinityraider.agricraft.core.CoreHandler.init(CoreHandler.java:92)
	at com.infinityraider.agricraft.proxy.IProxy.initEnd(IProxy.java:38)
	at com.infinityraider.infinitylib.InfinityMod.init(InfinityMod.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:805)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:334)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Vaygrim** [comment]
"AgriCraft-2.0.0-0.9.0-a16" has been pulled from Curse. So I can't keep this existing version until you get this crash bug fixed, if I try to update my modpack. WONDERFUL.

Can we please get this version restored to the version list?

**Comment by Psycholiquid71** [comment]
My server is down also. as it wants me to use version 18a so my server got updated and my modpack wont update.

**Comment by zackeezy** [comment]
I don't know if this will help, but here's my crash log: https://pastebin.com/P6cP65jz
